### ISSUE TITLE
Error: Command /bin/sh failed with exit code 127

### ISSUE THREAD

**Issue by HZZJL** [khoren93/SwiftHub#15]
Command /bin/sh failed with exit code 127

**Comment by wyman2016** [comment]
I have the same problem

**Comment by khoren93** [comment]
Can you provide more information? Xcode and CocoaPods versions.
Thanks for issue!

**Comment by wyman2016** [comment]
xcode: Version 10.2.1 
cocopods: 1.5.3
error msg:
` /Users/pxb/Library/Developer/Xcode/DerivedData/SwiftHub-awaevfgeokohkbdbqzanphnxlsdc/Build/Intermediates.noindex/SwiftHub.build/Debug-iphonesimulator/SwiftHub.build/Script-C762C6261E1D422B00C09EBD.sh: line 2: /Users/pxb/Downloads/SwiftHub-master: is a directory`

**Comment by BoxDengJZ** [comment]
@wyman2016 , one more

**Comment by khoren93** [comment]
Hi @BoxDengJZ 
I updated building instructions, can you clone again and follow the [instructions](https://github.com/khoren93/SwiftHub#building-and-running)?
Thanks.

**Comment by BoxDengJZ** [comment]
I fixed by delete Fabric and Crashlytics in PodFile , and then I delete the Fabric script in Build Phases.
I also delete SwiftLint script in  Build Phases at hand.

Then OK.

I run some problems in building, to get this , I run `bundle exec pod install --repo-update`

I will try clone again and follow the instructions

**Comment by BoxDengJZ** [comment]
Your instruction is not working in my case

```

 bundle exec fastlane setup
[✔] 🚀 
[10:17:58]: ------------------------------
[10:17:58]: --- Step: default_platform ---
[10:17:58]: ------------------------------
[10:17:58]: Driving the lane 'ios setup' 🚀
[10:17:58]: --------------------------------------------------------------------
[10:17:58]: Step: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
[10:17:58]: --------------------------------------------------------------------
[10:17:58]: $ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
[10:19:14]: ▸ curl: (7) Failed to connect to raw.githubusercontent.com port 443: Operation timed out
[10:19:16]: ▸ /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:91:in `block in materialize': Could not find unf_ext-0.0.7.5 in any of the sources (Bundler::GemNotFound)
[10:19:16]: ▸ from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:85:in `map!'
[10:19:16]: ▸ from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:85:in `materialize'
[10:19:16]: ▸ from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:170:in `specs'
[10:19:16]: ▸ from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:237:in `specs_for'
[10:19:16]: ▸ from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:226:in `requested_specs'
[10:19:16]: ▸ from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:108:in `block in definition_method'
[10:19:16]: ▸ from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:20:in `setup'
[10:19:16]: ▸ from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler.rb:107:in `setup'
[10:19:16]: ▸ from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/setup.rb:20:in `<top (required)>'
[10:19:16]: ▸ from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
[10:19:16]: ▸ from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
+------------------+-----------+
|         Lane Context         |
+------------------+-----------+
| DEFAULT_PLATFORM | ios       |
| PLATFORM_NAME    | ios       |
| LANE_NAME        | ios setup |
+------------------+-----------+
[10:19:16]: Exit status of command '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"' was 1 instead of 0.
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Operation timed out
/Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:91:in `block in materialize': Could not find unf_ext-0.0.7.5 in any of the sources (Bundler::GemNotFound)
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:85:in `map!'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:85:in `materialize'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:170:in `specs'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:237:in `specs_for'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:226:in `requested_specs'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:108:in `block in definition_method'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:20:in `setup'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler.rb:107:in `setup'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/setup.rb:20:in `<top (required)>'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'


+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 💥   | /usr/bin/ruby -e       | 77          |
|      | "$(curl -fsSL          |             |
|      | https://raw.githubuse  |             |
|      | rcontent.              |             |
+------+------------------------+-------------+

[10:19:16]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...


#######################################################################
# fastlane 2.122.0 is available. You are on 2.120.0.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################

2.122.0 Improvements
* [action] Added `format` option to `swiftlint` action (#14643) via Bruno Guidolim
* [action] create_pull_request add assignees option (#14637) via Kaito Watanabe
* [action] increment_version_number: Allow version without patch number (#14615) via Dunya Kirkali
* [pilot] Trim leading zeros in app_version in wait_for_build_processing_to_be_complete (#14691) via Edward Lai
* [supply] add API error logging and spec for supply (#14695) via Stefan Natchev
* [action] slather: Change binaryFile data type from Bool to optional String (#14677) via Robert Bauer
* [scan] spec_helper refactoring and fixing Scan tests (#14503) via Artem Sheremet
* [actions] New action `validate_play_store_json_key` (#14659) via Jan Piotrowski
* [action] Fix latest testflight build number problems / expired build scenario (#14683) via Ram
* [action] dded public key and note parameters to BuildAndUploadToAppetize. (#14631) via DanAtApex
* [action] update_app_identifier fails to search for curly brace variables in Info.plist (#14687) via Daniel Jankowski
* [spaceship] Feature to troubleshoot to_json issues, related to #13608 (#14682) via Jerome Lacoste
* [actions] extract shared code from setup_travis and setup_circle_ci actions (#14346) via Daniel Jankowski
* [action] Fix increment_build_number precondition issue (#14409) via Daniel Jankowski
* [spaceship] require pathname needed when not using bundler and requiring spaceship directly (#14667) via Josh Holtz

2.121.1 Improvements
* [deliver] screenshots are binary data, write as such (#14655) via Jan Piotrowski
* [action] app_store_build_number (and latest_testflight_build_number) don't raise error if using :initial_build_number (#14654) via Josh Holtz
* [spaceship] Authentication documentation (#14524) via Jan Piotrowski
* [deliver] fix ipad 3rd gen naming to prevent future collisions (#14653) via Josh Holtz
* [frameit] add missing documentation for title_min_height option (#14651) via Bruno Virlet
* [pilot] fix typo in message (#14646) via Piet Jaspers

2.121.0 Improvements for deliver, spaceship, and actions
* [action] allow modify_services to enable data_protection (#14571) via martinkasa
* [deliver] apple tv privacy policy upload and download handling added (#14569) via aniketgaur
* [deliver] iPad Pro (12.9-inch) (3rd generation) ambiguity resolution (#14576) via Viktoras Laukevičius
* [spaceship] make Spaceship::Tunes::DisplayFamily main data source for screenshot information (#14574) via Liam Nichols
* [action] cert: Prevent from crash when keychain_path param wasn't passed (#14620) via Dmitrii Celpan
* [frameit] fix frameit percentage padding (#14596) via Christophe Wagner
* [action] pod_lib_lint: Add support for use_module_headers and subspecs (#14599) via Raymond Hoagland
* [action] app_store_build_number: Pass teamID when selecting itunes team (#14604) via Dmitrii Celpan
* [spaceship] Include 'DES' cookie into FASTLANE_SESSION (#14301) (#14525) via Maksym Grebenets
* [spaceship] Automate phone number selection for "request code via SMS" in 2FA with `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` env var (#14436) via Jan Piotrowski
* [deliver] Test Deliver::AppScreenshot methods and fix uncovered bugs (#14588) via Liam Nichols
* [action] Post line break characters as actual interpreted line break through slack integration (#14612) via Albert
* [action] artifactory: Add a read timeout option (#14580) via Raymond Hoagland
* [action] pod_lib_lint: Add new cocoapods 1.7 parameters of the lint command (#14579) via Martin Fiebig
* [action] sonar: new optional param for branch name (#14611) via Husyn
* [action] register_devices changed to actions/register_devices/ (#14582) via Morten Bøgh
* [deliver] upload_screenshots_spec to test screenshot collection (#14533) via Liam Nichols
* [deliver] Fix builds whose versions have components with leading zeros infinitely wait for submission (#14513) via Justin Hill

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `bundle update fastlane`
Traceback (most recent call last):
	28: from /Users/vv/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
	27: from /Users/vv/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
	26: from /Users/vv/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `<main>'
	25: from /Users/vv/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `load'
	24: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/bin/fastlane:23:in `<top (required)>'
	23: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	22: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	21: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	20: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	19: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	18: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	17: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	16: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	15: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	14: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	13: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	12: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	11: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	10: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	 9: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	 8: from Fastfile:22:in `block (2 levels) in parsing_binding'
	 7: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/fast_file.rb:186:in `sh'
	 6: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/fast_file.rb:191:in `sh'
	 5: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 4: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/fast_file.rb:192:in `block in sh'
	 3: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/helper/sh_helper.rb:16:in `sh_no_action'
	 2: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	 1: from /Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/vv/.rvm/gems/ruby-2.6.0/gems/fastlane-2.120.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Operation timed out
/Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:91:in `block in materialize': Could not find unf_ext-0.0.7.5 in any of the sources (Bundler::GemNotFound)
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:85:in `map!'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:85:in `materialize'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:170:in `specs'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:237:in `specs_for'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:226:in `requested_specs'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:108:in `block in definition_method'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:20:in `setup'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler.rb:107:in `setup'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/bundler/setup.rb:20:in `<top (required)>'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/vv/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'


```

**Comment by srn214** [comment]
### Run the project to report an error
> Command /bin/sh failed with exit code 1
>
> ![Snip20190730_5](https://user-images.githubusercontent.com/14295747/62096746-536e2f00-b2b7-11e9-80a6-3f66f05917e0.png)

**Comment by XavierLost** [comment]
https://github.com/apollographql/apollo-ios/issues/1040

**Comment by XavierLost** [comment]
pod 'Apollo'  #, '0.28.0'  # https://github.com/apollographql/apollo-ios
